### ISSUE TITLE
Python 3 지원

### ISSUE THREAD

**Issue by mete0r** [mete0r/pyhwp#112]
https://wiki.documentfoundation.org/ReleaseNotes/4.0#API_Changes

내장 파이썬이 2.6에서 3.3으로 변경 ㅠㅠ

**Comment by JoonyoungYi** [comment]
안녕하세요? 혹시, 언제쯤 Python3 도 지원될까요?

**Comment by soorichu** [comment]
안녕하세요, 파이썬 3으로 변경은 이제 힘든 걸까요...ㅠㅠ 
좋은 프로그램 공개해주셔서 정말 감사합니다.

**Comment by JoonyoungYi** [comment]
@soorichu 개발자님께서 바쁘신가 봅니다. 저 같은 경우에는 virtualenvironment를 하나 더 생성해서, python2로 셋팅한 다음에 <venv_path>/bin/python3 pyhwp~~~ 이런식으로 사용하고 있습니다. 이 방식이 현재로서는 제일 괜찮은 방법일 듯 합니다.

**Comment by soorichu** [comment]
@JoonyoungYi  그게 python3으로 만든 프로그램이 있는데 거기다 같이 넣고 싶어서요.ㅠㅠ 
답변 감사드립니다. ^^

**Comment by mete0r** [comment]
0.1b12 버젼에서 Python 3 지원합니다.
