### ISSUE TITLE
Decrypt hwp

### ISSUE THREAD

**Issue by nvb13** [mete0r/pyhwp#154]
Hello. Please help me. How can i decrypt hwp5 file by this util ( i have a file and i know password). 
1)I take sha1 from password
2)Convert it to Upper
3)Convert utf8 to utf16le
4)conver bin to ASCII

after it i got key like: 5A9B7508
What next? please help.

**Comment by mete0r** [comment]
Sorry, I have no information on that subject, i.e., missing bits from the "authoritative" spec documents.

But it's interesting. Based on what source of information, did you take those steps?

**Comment by nvb13** [comment]
I was thin that https://github.com/mete0r/pyhwp/blob/82aa03eb3afe450eeb73714f2222765753ceaa6c/pyhwp-tests/hwp5_tests/test_distdoc.py this code can decrypt Section0. I was mistake? And this algorytm https://groups.google.com/forum/#!msg/hwp-foss/d2KL2ypR89Q/lCTkebPcIYYJ i can not read in Korean.

**Comment by mete0r** [comment]
I see. I think you may be confused with two distinct features of the HWP format version 5: Distribute-only documents (non-editable without a password) and password-protected ones(non-readable without a password). While the former have embedded keys, with which we can decrypt their contents (which your links are about), unfortunately decryption mechanism for the latter is unknown to public.

So if your file is the former case you can decrypt its content with pyhwp, requiring no manual key provision. If it's not, there is no way for me to help.

You can identify them as following command:

    $ hwp5proc cat --vstreams YOURFILE.hwp FileHeader.txt

    ccl: 0
    cert_drm: 0
    cert_encrypted: 0
    cert_signature_extra: 0
    cert_signed: 0
    compressed: 1
    distributable: 0
    drm: 0
    history: 0
    password: 0               # <--- If this is 1, it is a password encrypted file,
                                     which pyhwp cannot decrypt the contents currently.
    script: 0
    signature: HWP Document File
    version: 5.0.1.7
    xmltemplate_storage: 0
