### ISSUE TITLE
no OleStorage implementation available - window

### ISSUE THREAD

**Issue by ktj4820** [mete0r/pyhwp#157]
환경은 window 2013 server, python2.7
lxml 설치완료 
pypy 설치완료 

hwp5proc 실행시 아래와 같은 오류가 나옵니다. 어떻게야할까요? 

hwp5proc ls 1F.hwp
Traceback (most recent call last):
  File "C:\Python27\Scripts\hwp5proc-script.py", line 11, in <module>
    load_entry_point('pyhwp==0.1b9', 'console_scripts', 'hwp5proc')()
  File "c:\python27\lib\site-packages\hwp5\proc\__init__.py", line 154, in main
    return mod.main(argv)
  File "c:\python27\lib\site-packages\hwp5\proc\__init__.py", line 101, in main
    return f(args)
  File "c:\python27\lib\site-packages\hwp5\proc\ls.py", line 92, in main
    hwpfile = open_hwpfile(args)
  File "c:\python27\lib\site-packages\hwp5\proc\__init__.py", line 165, in open_hwpfile
    hwpfile = Hwp5File(filename)
  File "c:\python27\lib\site-packages\hwp5\filestructure.py", line 484, in __init__
    stg = Hwp5FileBase(stg)
  File "c:\python27\lib\site-packages\hwp5\filestructure.py", line 181, in __init__
    stg = OleStorage(stg)
  File "c:\python27\lib\site-packages\hwp5\storage\ole.py", line 31, in __init__
    assert impl_class is not None, 'no OleStorage implementation available'
AssertionError: no OleStorage implementation available

**Comment by ktj4820** [comment]
pip install OleFileIO_PL==0.23 로 하니까 에러는 없네요.

**Comment by mete0r** [comment]
네, 문서에 반영해야겠네요. 알려주셔서 감사합니다.

**Comment by marunguy** [comment]
소스하고 설명하고 다른 것 같습니다.
`CHANGES` 파일을 보면 `OleFileIO_PL`를 `olefile` 패키지로 변경한 것으로 나옵니다.
```
0.1b8 (2014-11-03)
------------------

- hwp5view: experimental viewer with webkitgtk+ 
- hwp5proc: xml --formats ("flat", "nested")
...
- olestorage: use new olefile instead of OleFileIO_PL
```
또한, `setup.py` 를 살펴보면 python 2.7 일 경우 `OleFileIO_PL`가 아닌 `olefile` 패키지에 의존하는 게 맞는 것 같습니다.
```python
def prepare_runtime_metadata(metadata):
    ....
    if 'java' not in sys.platform and sys.version < '3':
        install_requires = metadata.get('install_requires', [])
        if sys.version_info < (2, 6):
            # OleFileIO_PL 0.30 has dropped Python 2.5 support
            olefileio = 'OleFileIO_PL >= 0.23'
            olefileio += ', < 0.30'
        else:
            olefileio = 'olefile >= 0.40'
        install_requires.append(olefileio)
        metadata['install_requires'] = install_requires
    ....
```

**Comment by marunguy** [comment]
테스트PC에서 `OleFileIO_PL` 패키지가 설치가 되지 않아서 `olefile` 패키지를 강제로 사용하도록 수정했습니다.
hwp2txt 는 잘 동작하는 것 같습니다.
```python
# hwp5 모듈 임포트 하긴 전에 
import sys
import olefile
sys.modules['OleFileIO_PL'] = olefile
....
```

**Comment by ildar** [comment]
> pip install OleFileIO_PL==0.23

is not isntallable:
>    copying build/lib/OleFileIO_PL.py -> /usr/lib/python2.7/site-packages
>    error: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/OleFileIO_PL.py'
