### ISSUE TITLE
HWP Python3에서 쓰고 싶은데 안되네요.

### ISSUE THREAD

**Issue by liveinseoul** [mete0r/pyhwp#163]
Python3에서 작동하는 HWP text추출 라이브러리를 부탁드립니다. 

HWP파일 여러개가 있을 때, 내용에 나오는 글자를 일부 추출하고 제목과 비교하고 싶어서 
검색하다 pyhwp를 발견하고 기뻤는데요, 
안타깝게도 pyhwp를 설치하려고 했는데 에러가 나옵니다. 

Python3에서도 작동하는 pyhwp가 필요합니다.
혹시 여력이 되시면 부탁드립니다. 감사합니다.

**Comment by mete0r** [comment]
올해로 Python 2.7 지원이 끝나기 때문에, 서둘러 Python 3로 이행하려 하고 있습니다 :)

감사합니다.

**Comment by mete0r** [comment]
0.1b12 버젼에서 Python 3 지원합니다.
