### ISSUE TITLE
hyperlink 텍스트가 포함된 hwp파일 변환 시 해당 컨텐츠가 누락되는 문제

### ISSUE THREAD

**Issue by limpCODER** [mete0r/pyhwp#164]
우연히 상기 제목과 같은 문제를 발견하게 되었습니다.

한글문서(hwp5) 내부에 하이퍼링크가 걸려있는 텍스트가 존재하는 경우, hwp5odt, hwp5html 등으로 변환 시 해당 텍스트 전체가 누락되는 문제에 대한 샘플 파일을 아래에 첨부합니다.

[link_sample.zip](https://github.com/mete0r/pyhwp/files/2899324/link_sample.zip)

**Comment by mete0r** [comment]
이슈를 왜 닫으셨는지는 모르겠지만, 보고 감사합니다.

링크해주신 파일로 확인해보도록 하겠습니다.

**Comment by limpCODER** [comment]
안녕하세요, meto0r님

이렇듯 확인하시고 메일까지 주실 줄은 몰랐습니다.
소스까지 다 공개해주셨는데도 너무 밑도 끝도 없이 안 됩니다라고만 글을 남겨서 태도가 잘못된 것 같아서
IDE깔고 소스 코드 좀 찾아보고 다시 말씀드릴 생각이었는데.. 어차피 들킬 것을 공연한 짓을 했다 싶어 엄청 민망하네요 (...)

첨언 드리자면 하이퍼링크, 차트, 수식 등 정부 및 교육기관에서 많이 사용되는 부분들이 누락되어 살펴보던 중이었습니다.
실력이 일천하여 아직 감도 못 잡고 디버깅 한 번 못 돌려본 상태이긴 하지만서도 혹여나 원인을 찾게 되면 말씀드리겠습니다.

좋은 하루 되세요.
김갑기 드림

2019년 2월 26일 (화) 오후 5:34, mete0r <notifications@github.com>님이 작성:
