### ISSUE TITLE
pip install --pre pyhwp 설치시 hypua2jamo모듈 설치 실패

### ISSUE THREAD

**Issue by karoscha** [mete0r/pyhwp#166]
root@ab957c3f3d0b:/# pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 6.4MB/s 
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.0.3
root@ab957c3f3d0b:/# pip install --pre pyhwp
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pyhwp
  Downloading https://files.pythonhosted.org/packages/39/0f/cec7d0af3476f036faadda49be840d432b807b9c80b8c1026bbc5f520323/pyhwp-0.1b11.tar.gz (211kB)
    100% |████████████████████████████████| 215kB 9.0MB/s 
Collecting docopt>=0.6 (from pyhwp)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting hypua2jamo>=0.4.4 (from pyhwp)
  Downloading https://files.pythonhosted.org/packages/57/92/3dafa90a0b15556dc72ca136f30af047b4f14b8c4cc652362f4dda356419/hypua2jamo-0.4.4.tar.gz (694kB)
    100% |████████████████████████████████| 696kB 9.7MB/s 
Collecting lxml (from pyhwp)
  Downloading https://files.pythonhosted.org/packages/89/51/a8a6cdb8a084d32dbc9bda94623dc35310ae2002be57de8702a1703c0026/lxml-4.3.3-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 3.8MB/s 
Collecting cryptography (from pyhwp)
  Downloading https://files.pythonhosted.org/packages/c3/c1/cf8665c955c9393e9ff0872ba6cd3dc6f46ef915e94afcf6e0410508ca69/cryptography-2.6.1-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 6.8MB/s 
Collecting olefile>=0.43 (from pyhwp)
  Downloading https://files.pythonhosted.org/packages/34/81/e1ac43c6b45b4c5f8d9352396a14144bba52c8fec72a80f425f6a4d653ad/olefile-0.46.zip (112kB)
    100% |████████████████████████████████| 112kB 10.7MB/s 
Collecting cffi>=1.0.0 (from hypua2jamo>=0.4.4->pyhwp)
  Downloading https://files.pythonhosted.org/packages/9d/6f/aea9f5559fb593da07ff34e67513bd62483b45715b4a5f5fae6a0a5792ea/cffi-1.12.2-cp27-cp27mu-manylinux1_x86_64.whl (413kB)
    100% |████████████████████████████████| 419kB 10.8MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography->pyhwp)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 12.1MB/s 
Collecting enum34; python_version < "3" (from cryptography->pyhwp)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography->pyhwp)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography->pyhwp)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.0.0->hypua2jamo>=0.4.4->pyhwp)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 10.3MB/s 
Building wheels for collected packages: pyhwp, docopt, hypua2jamo, olefile, pycparser
  Building wheel for pyhwp (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/9a/e3/c4/377313ab682f497d11109d11577fe360c5e539fa48c8a2f44a
  Building wheel for docopt (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Building wheel for hypua2jamo (setup.py) ... error
  Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-UOEbsh/hypua2jamo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-1EZ4la --python-tag cp27:
  running bdist_wheel
  running build
  error: [Errno 2] No such file or directory
  
  ----------------------------------------
  Failed building wheel for hypua2jamo
  Running setup.py clean for hypua2jamo
  Building wheel for olefile (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/4b/f4/11/bc4166107c27f07fd7bba707ffcb439619197638a1ac986df3
  Building wheel for pycparser (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pyhwp docopt olefile pycparser
Failed to build hypua2jamo
Installing collected packages: docopt, pycparser, cffi, hypua2jamo, lxml, asn1crypto, enum34, ipaddress, six, cryptography, olefile, pyhwp
  Running setup.py install for hypua2jamo ... error
    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-UOEbsh/hypua2jamo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-eqIBXz/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    error: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-UOEbsh/hypua2jamo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-eqIBXz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-UOEbsh/hypua2jamo/
root@ab957c3f3d0b:/# 

hypua2jamo 모듈 설치부분에서 오류가 발생합니다. 결론적으로 말씀드리자면 pip 설치가 아닌
git에서 프로젝트를 클론하여 python setup.py 을 통한 인스톨을 실행할 시에는 잘 설치가 되더군요. 제가 python은 시작단계라 조언은 드릴수 없고 이런 문제점이 있다고만 말씀드리겠습니다.
그리고 제가 보기에는 hypua2jamo모듈이 단독으로 배포되는것은 아닌듯 한데 어떻게 하신건지 궁금하네요.

**Comment by mete0r** [comment]
보고 감사드립니다.

최근 업데이트한 hypua2jamo 0.4.4 패키지는 C 확장 모듈이 포함되어 있어, MS 윈도우 外 환경에서 설치 시 CMake, make 및 C 컴파일러가 필요합니다. (관련 이슈: https://github.com/mete0r/hypua2jamo/issues/2) 아마도 그 문제일 것으로  짐작하는데, 괜찮으시면 확인 부탁드립니다.

이번 주말 쯤 workaround 를 적용한 pyhwp, hypua2jamo 를 릴리즈할 예정입니다.

**Comment by mete0r** [comment]
0.1b12 버젼에서 hypua2jamo 패키지에 대한 의존성을 제거했습니다. 더 이상 한양 PUA 코드를 유니코드 자모로 변환하여 출력하지 않습니다.

**Comment by karoscha** [comment]
답변이 늦어 죄송합니다. 설치환경은 linux docker 기반의 centos 7.5에서 진행하였고 pip를 사용한 인스톨에서 해당 내용이 출력된 것입니다. 참고로  python은 수동 설치로 gcc모듈 및 make 등 yum으로 설치된 상태에서 git 으로 다운받아서 python setup.py 로 설치 진행했습니다. 답변이 도움이 되었으면 하네요. 수고하세요

**Comment by karoscha** [comment]
아 또 linux docker기반 docker.io/python:2.7.14(debian 8) 환경에서 git으로 받아 설치 할때는 문제없이 설치되었습니다. 수고하세요^^
